# Generated by Django 5.1.6 on 2025-02-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cafeteria',
            new_name='Kafedra',
        ),
    ]
