# Generated by Django 5.1.6 on 2025-02-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_rename_cafeteria_kafedra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='cafeteria',
            new_name='kafedra',
        ),
    ]
